### PR TITLE
Build responsive website for the repository

### PR DESCRIPTION
**Pull request by arhum602**
- Used Bootstrap for responsiveness

- Utilized SCSS for smooth transition

- Would likely to add more features over time

Attached photos of the current state of the website

website1
website2
website3

### CODE REVIEW

**Comment by avinash201199** [comment]
put the index.html file in the main page only to host it by using github pages , do not put in inside any folder

**Comment by arhum602** [comment]
@avinash201199 I understand. But I will do that after I make few more changes and add some more sections.

**Comment by avinash201199** [comment]
> @avinash201199 I understand. But I will do that after I make few more changes and add some more sections.

okay , let me know once done

**Comment by arhum602** [comment]
@avinash201199 Its done you just have to accept and close this pr. Then just drag the index file to root and it will work, already made the required changes to files.

**Pull request merged**
