### PR TITLE
Issue #1 : Added my portfolio(Jyotimoy Kashyap)

### PR DESCRIPTION
**Pull request by JyotimoyKashyap**
I have checked the commits. 

Please review the changes and merge my pull request labelling "hacktoberfest-accepted"

### CODE REVIEW

**Comment by avinash201199** [comment]
@JyotimoyKashyap  please follow for more such repo

**Comment by JyotimoyKashyap** [comment]
I had one question actually @avinash201199 , I am into open source for the first time, and in my profile of hacktoberfest I can see that those pull requests which is merged it says matures in 14 days, what does that mean? I will be really grateful if you could just give me some idea, how it works.

**Comment by avinash201199** [comment]
I'm not sure , may be they will review it or it will take time to reflect.

**Comment by JyotimoyKashyap** [comment]
Oh okay, thank you so much, as this is my first time, maybe I don't want to get disappointed. Thanks for replying, I wasn't expecting such a quick reply, knowing the circumstances that, you must have a lot of pull requests to merge and review in the DSA repo.

Thank You really!

**Comment by avinash201199** [comment]
yeah , trying my best .
I have to also make 4 pr as a participant .

**Pull request merged**
