### PR TITLE
Added Landing Page. 

### PR DESCRIPTION
**Pull request by nidhi8404**
Updated index.html by adding new portfolio links to the main grid section, making it easier to access individual portfolios. Also, edited the README.md to include simple instructions for contributors on how to add their portfolio folder and update index.html with the correct link.

image

### CODE REVIEW

**Comment by Harshh18** [comment]
Hey @nidhi8404 , I just wanna ask you how did your PR passed the Vercel check? Coz, I have tried somethings after my PR, still I can't pass those checks.

**Comment by avinash201199** [comment]
thank you for your valuable contribution

**Comment by avinash201199** [comment]
@nidhi8404 
image
can you point each card to respective folder path because these are not deployed so we don't have live link but we can give github folder link

**Comment by nidhi8404** [comment]
@Harshh18 to successfully deploy a project on Vercel, it needs a clear project structure and valid code that compiles without errors. Do check for errors and try to resolve them.

**Pull request merged**
